apiVersion: v2
name: prometheus
description: Prometheus via kube-prometheus-stack
type: application
version: 0.1.0
appVersion: "0.75.0"
dependencies:
  - name: kube-prometheus-stack
    version: "56.6.0"
    repository: https://prometheus-community.github.io/helm-charts
