replicaCount: 1

image:
  repository: cloudflare/cloudflared
  tag: "2025.11.1"
  pullPolicy: IfNotPresent

tunnel:
  id: 86d372da-84e0-4a72-a13b-4933565208d9
  credentialsSecretName: cloudflared-creds

# Matches Cloudflare docs
config:
  noAutoupdate: true
  logLevel: info

ingress:
  - hostname: argocd.curtfamily.org
    service: http://argocd-server.argocd.svc.cluster.local:80

  - hostname: grafana.curtfamily.org
    service: http://grafana.monitoring.svc.cluster.local:80

  # Default fallback
  - service: http_status:404
