replicaCount: 1
adminUser: admin
adminPassword:
  existingSecret: grafana-admin
  key: admin-password
persistence:
  enabled: false
  size: 5Gi
ingress:
  enabled: false
  hosts:
    - grafana.curtfamily.org
image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent
